### PR TITLE
Runtime Initialization

### PR DESCRIPTION
**Pull request by fdaniels110**
Current runtime initialization does not correctly initialize the runTime var for Processes according to the  requirements on the HW sheet. This change should allow it to initialize according to guidelines.

### CODE REVIEW

**Comment by flip40** [comment]
I would recommend a separate branch for this next time. This has nothing to do with the Priority_Non-premeptive branch, and now making commits to this branch (perhaps for your work in one of the HPF classes) will show up in this PR, which has nothing to do with that work, but I digress. +1 on the code changes.

**Comment by fdaniels110** [comment]
My bad. I was beginning working and I saw that detail. Didn't know that it would keep the same PR. I'll just reinitialize the branch.

**Comment by flip40** [comment]
No worries, just letting you know. You could keep this branch if you want, it won't matter once the PR has been made and merged. But while the PR sits, any commits on the branch will be added to the PR for that branch.

**Comment by flip40** [comment]
Actually I lied slightly, go ahead and make a new branch just to be sure you have all the new updates to the master branch (which depends on when this branch was made).

**Pull request merged**
